<a href="https://colab.research.google.com/github/IffatMaab0/Deep-Learning-For-Computer-Vision/blob/main/TensorFlow/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tens_1d = tf.constant([
                       [
                           [1,2,3,4],
                           [2,3,4,5]
                       ],
                       [
                           [1,2,3,4],
                           [2,3,4,5]
                        ]
                     ])
print(tens_1d.ndim)

3


In [ ]:
tens_4d = tf.constant([
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ],
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ],
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ]


])
print(tens_4d)

tf.Tensor(
[[[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]


 [[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]


 [[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]], shape=(3, 2, 2, 4), dtype=int32)
