<a href="https://colab.research.google.com/github/IffatMaab0/Deep-Learning-For-Computer-Vision/blob/main/TensorFlow/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [6]:
tens_3d = tf.constant([
                       [
                           [1,2,3,4],
                           [2,3,4,5]
                       ],
                       [
                           [1,2,3,4],
                           [2,3,4,5]
                        ]
                     ], dtype = tf.float64)
print(tens_3d)

tf.Tensor(
[[[1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]]], shape=(2, 2, 4), dtype=float64)


In [ ]:
tens_4d = tf.constant([
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ],
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ],
    [
        [
            [1,2,3,4],
            [0,9,8,7]
        ],
        [
            [1,2,3,4],
            [0,9,8,7]
        ]
    ]


])
print(tens_4d)

tf.Tensor(
[[[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]


 [[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]


 [[[1 2 3 4]
   [0 9 8 7]]

  [[1 2 3 4]
   [0 9 8 7]]]], shape=(3, 2, 2, 4), dtype=int32)


In [3]:
tensor_4d = tf.constant([
    [
        [
            [1,7,8],
            [2,3,7],
            [5,7,3]
        ],
        [
            [4,8,5],
            [5,1,3],
            [6,2,0]
        ]
    ],
    [
        [
            [5,3,2],
            [4,5,4],
            [6,9,8]
        ],
        [
            [2,4,2],
            [5,4,9],
            [3,4,5]
        ]
    ]
])
print(tensor_4d)

tf.Tensor(
[[[[1 7 8]
   [2 3 7]
   [5 7 3]]

  [[4 8 5]
   [5 1 3]
   [6 2 0]]]


 [[[5 3 2]
   [4 5 4]
   [6 9 8]]

  [[2 4 2]
   [5 4 9]
   [3 4 5]]]], shape=(2, 2, 3, 3), dtype=int32)
