<a href="https://colab.research.google.com/github/IffatMaab0/Deep-Learning-For-Computer-Vision/blob/main/TensorFlow/Tensor_Maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [1]:
x = [1,2,3]
tf.expand_dims(x, axis=0)

In [4]:
x = tf.constant([-5, 3, -2])

tf.math.abs(x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 3, 2], dtype=int32)>

In [5]:
x = tf.constant([2,3,4])

tf.math.square(x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  9, 16], dtype=int32)>

In [6]:
x = tf.constant([4.0, 9.0, 16.0])

tf.math.sqrt(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [7]:
a = tf.constant([1,5,3])
b = tf.constant([2,4,10])

tf.math.maximum(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  5, 10], dtype=int32)>

In [8]:
x = tf.constant([1,2,3,4])

tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
x = tf.constant([
    [1,2],
    [3,4]
])

tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [11]:
x = tf.constant([5,20,8])
tf.math.argmax(x)

<tf.Tensor: shape=(), dtype=int64, numpy=1>